name: CI/CD Pipeline - Web App Medicine (Aula 05)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'DevOps/Aula_05/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'DevOps/Aula_05/**'

# ADICIONE ESTA SEÇÃO
permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DevOps/Aula_05

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Baixa todo o histórico do Git para evitar erros com comandos git